// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  GlobalDeclaration = 2,
  VariableDeclaration = 3,
  TypeSpecifier = 4,
  Identifier = 5,
  float = 6,
  vec3 = 7,
  Struct = 8,
  struct = 9,
  StructDeclarationList = 10,
  StructDeclaration = 11,
  StructDeclarationSpecifier = 12,
  PrivateIdentifier = 13,
  SingleDeclaration = 14,
  DeclarationSpecifier = 15
