// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,float:12, vec3:14, struct:18}
export const parser = LRParser.deserialize({
  version: 14,
  states: "%dOVQPOOOOQO'#C`'#C`ObQPO'#C_OjQPO'#C^OoQPO'#CdQOQPOOOOQO'#Ck'#CkOOQO'#Cj'#CjOwQPO,58yOOQO,58x,58xO!PQPO,59OO!_QPO,59OO!dQPO'#CnO!iQPO1G.eO!qQPO'#CgOOQO'#Cl'#ClO!vQPO'#CfO#UQPO1G.jO!PQPO1G.jOOQO,59Y,59YOOQO-E6l-E6lOOQO'#Ci'#CiOOQO'#Ch'#ChO#ZQPO'#CsO#cQPO,59ROOQO-E6j-E6jOOQO7+$U7+$UO#hQPO7+$UO!qQPO'#CmO#mQPO,59_OOQO1G.m1G.mOOQO<<Gp<<GpOOQO,59X,59XOOQO-E6k-E6k",
  stateData: "#u~OeOS~OUPOVPOXSO~OTUOiRX~OiXO~OTZOfYO~Oh[OiRa~OUPOVPOXSOjYP~OfbO~OTUO~Oh[OiRi~OTeO~OUPOVPOXSOjYX~OjjO~OhlOigX~OinO~OjoO~OhlOiga~O",
  goto: "#UhPPiloPPPwP}!T!Y!`!d!j!n!u!{PPPP#RRTORROQQOV^Y`bXPOY`bQaYRkbV_Y`bQg^RplTf^lQWQRc[TVQ[S`YbRi`QmgRqmQ]WRd]Rh^",
  nodeNames: "⚠ Program GlobalDeclaration VariableDeclaration TypeSpecifier Identifier float vec3 Struct struct StructDeclarationList StructDeclaration StructDeclarationSpecifier PrivateIdentifier SingleDeclaration DeclarationSpecifier",
  maxTerm: 26,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "#r~RaX^!Wpq!W|}!{!]!^#Q!c!}#V#R#S#V#T#o#V#o#p#h#q#r#m#y#z!W$f$g!W#BY#BZ!W$IS$I_!W$I|$JO!W$JT$JU!W$KV$KW!W&FU&FV!W~!]Ye~X^!Wpq!W#y#z!W$f$g!W#BY#BZ!W$IS$I_!W$I|$JO!W$JT$JU!W$KV$KW!W&FU&FV!W~#QOh~~#VOi~~#[ST~!Q![#V!c!}#V#R#S#V#T#o#V~#mOf~~#rOj~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 5, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
